
# Theme
[general]
import = ["/home/hurodor/.config/alacritty/tokyo-night_tweak.toml"]
live_config_reload = true

[env]
GTK_THEME = "Tokyonight-Dark"

[window]
startup_mode = "Windowed"
decorations_theme_variant = "None"
opacity = 0.9
# decorations = "full"


[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 11
# blur = true

[mouse]
hide_when_typing = true
