
# Theme
[general]
import = ["~/.config/alacritty/tokyo-night_tweak.toml"]
# import = ["~/.local/share/nvim/lazy/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml"]
live_config_reload = true

[window]
startup_mode = "Windowed"
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9

# [window.padding]
# x = 10
# y = 10

[colors]
# draw_bold_text_with_bright_colors = true


[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 11
# blur = true

# [mouse]
# hide_when_typing = true

[selection]
save_to_clipboard = true

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[bell]
command = "None"
