
# Theme
[general]
import = ["/home/hurodor/.config/alacritty/tokyo-night_tweak.toml"]
live_config_reload = true

[window]
startup_mode = "Windowed"
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9


[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 11
# blur = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[bell]
command = "None"

