[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xacb0d0"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.cursor]
cursor = "0xFF261E"
text = "0xEBEBEB"

[colors.normal]
black = "0x32344a"
blue = "0x4376C1"
# blue = "#3e68d7" # nice
cyan = "0x4FBDCC"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "#c53b53"
white = "0x787c99"
yellow = "0xe0af68"


[colors.primary]
# background = "0x1a1b26"
# foreground = "0xa9b1d6"
background = '#222436'
foreground = '#c8d3f5'
