
# Theme
import = ["/home/hurodor/.config/alacritty/tokyo-night_tweak.toml"]
# import = ["/home/hurodor/.config/alacritty/tokyonight-moon-tweak.toml"]

[font]
size = 11

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"
