# start tmux if ssh and not allready in one
if [ ! "$TMUX" ] && [ -n "$SSH_CONNECTION" ]; then
    tmux new -A -s main 2>&1 > /dev/null
    command || exit 1
fi

source $HOME/.config/zsh/env.zsh
source $HOME/.config/zsh/ohmyzsh.zsh
source $HOME/.config/zsh/aliases.zsh

# Soruce local alias file if it exists. This is done after
# normal alias file to override if nesesary
LOCAL_ALIASES="$HOME/.aliases_local"
if [ -e  $LOCAL_ALIASES ]; then
    source $LOCAL_ALIASES
fi


