# start tmux if ssh and not allready in one
if [ ! "$TMUX" ] && [ -n "$SSH_CONNECTION" ]; then
    tmux new -A -s main 2>&1 > /dev/null
    command || exit 1
fi

# load custom fzf
export FZF_BASE="$HOME/.local/var/fzf"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.config/oh-my-zsh"

# Path to custom folder
export ZSH_CUSTOM="$HOME/.config/zsh"

# Set name of the theme to load
# ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_THEME=""

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# config autosuggestion color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
    vi-mode
    fzf
    github
)

# Change cache folder
ZSH_CACHE="$HOME/.cache/zsh/"
if [[ ! -d $ZSH_CACHE ]]; then
  mkdir -p $ZSH_CACHE 
fi
ZSH_COMPDUMP="$ZSH_CACHE/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
HISTFILE="$ZSH_CACHE/zsh_history"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Soruce local alias file if it exists. This is done after normal alias-file
# to override if nesesary
export LOCAL_ALIASES="$HOME/.aliases_local"
if [ -e $LOCAL_ALIASES ]; then
    source $LOCAL_ALIASES
fi

# Remove the (virtualenv-name) in the start of the shell prompt when activating
# virtualenvs. This is in the starship config
export VIRTUAL_ENV_DISABLE_PROMPT=1

eval "$(starship init zsh)"
