# start tmux if ssh and not allready in one
if [ ! "$TMUX" ] && [ -n "$SSH_CONNECTION" ]; then
    tmux new -A -s main 2>&1 > /dev/null
    command || exit 1
fi

# load custom fzf
# export FZF_BASE="$HOME/.local/var/fzf"
eval "$(mise activate zsh)"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.config/oh-my-zsh"

# Path to custom folder
export ZSH_CUSTOM="$HOME/.config/zsh"

# Theme is handled by starship instead (see starship/starship.toml)
ZSH_THEME=""

zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# config autosuggestion color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
    vi-mode
    fzf
    github
)

# Change cache folder
ZSH_CACHE="$HOME/.cache/zsh/"
if [[ ! -d $ZSH_CACHE ]]; then
  mkdir -p $ZSH_CACHE 
fi
ZSH_COMPDUMP="$ZSH_CACHE/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
HISTFILE="$ZSH_CACHE/zsh_history"

source $ZSH/oh-my-zsh.sh

# Soruce local alias file if it exists. This is done after normal alias-file
# to override if nesesary
export LOCAL_ALIASES="$HOME/.aliases_local"
if [ -e $LOCAL_ALIASES ]; then
    source $LOCAL_ALIASES
fi

# Remove the (virtualenv-name) in the start of the shell prompt when activating
# virtualenvs. This is in the starship config
export VIRTUAL_ENV_DISABLE_PROMPT=1

eval "$(starship init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

