#!/usr/bin/bash

LOCAL_BIN="$HOME/.local/bin"

binlink (){
    FILE_NAME=$(basename "$1")
    if [ -f $1 ]; then
        ln -s $(pwd)/$1 $LOCAL_BIN/$FILE_NAME
    fi
}

echo "Installing $1 to $LOCAL_BIN"
binlink $1

